export const fall2024 = 
{
    departments: ["CMSC", "PHYS"],
    classes: [
    {
        department: "CMSC",
        number: "388J",
        title: "Building Secure Web Applications",
        advisor: "Michael Marsh",
        facilitators: [ 
        { name: 'Chuck Peterson', email: 'cpeter11@umd.edu' },
        { name: 'Nikita Krupin', email: 'nkrupin@umd.edu' },
        ],
        description: "Explores tools such as Python, Flask, Django, MongoDB, Svelte, and React.",
        id: 200,
        website: "https://aspear.cs.umd.edu/388j",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398T",
        title: "Beyond Aesthetics: Accessible Frontend Design",
        advisor: "Evan Golub",
        facilitators: [ 
        { name: 'Somil Varshney', email: 'somilv@umd.edu' },
        { name: 'Sriman Selvakumaran', email: 'srimans@umd.edu' },
        ],
        description: "This course is intended to familiarize students with technologies and skills to build a modern website giving adequate consideration to inclusive design, emerging frameworks, design trends, and user experience. By the end of this course, students will have a polished portfolio website demonstrating their skill set and projects to peers and employers alike.",
        id: 209,
        website: "https://docs.google.com/document/d/162Oc21dKG7YkgTz7562JUeC9V04vu0osc4uCOya30ZI/edit#heading=h.fsz27mx8cgs3",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389O",
        title: "The Coding Interview",
        advisor: "Tom Goldstein",
        facilitators: [
        { name: 'Emmanuel Bautista', email: 'emanbautista410@gmail.com' },
        { name: 'Faadil Shaikh', email: 'fshaikh1@terpmail.umd.edu' },
        ],
        description: "Technical interviewing is a critical skill for acquiring internships and jobs. Students will gain a comprehensive, practical introduction to technical interviews. Students will be introduced to basic topics such as Big O and String Manipulation and later move into more complex topics such as Graphs and Dynamic Programming. Most in-class time will be spent on mock interviews to give real interview practice. The course facilitators are experienced in interviewing and have received internship/job offers from companies like Meta, Optiver, Bloomberg, Amazon, Apple, Microsoft, Databricks, Capital One, and more.",
        id: 210,
        website: "https://docs.google.com/document/d/1q2ecmjGJrZCpfkGZ72CthvUEbFpi1amySsZ-VSIojIg/edit#heading=h.9bydr0enr5nw",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389P",
        title: "Mastering the PM Interview",
        advisor: "Huaishu Peng",
        facilitators: [ 
        { name: 'Angelyn Pham', email: 'angpham@terpmail.umd.edu' },
        ],
        description: "Product Management is an interesting intersection of technology and business that students are given the opportunity to learn more about in this class. Students are introduced to the tools, techniques, and resources to nail their PM (Product Management) interviews. We'll be providing hands-on practice with PM specific topics including product design, analytical, and case questions. By the end of the class, you should be acing all your PM interviews!",
        id: 211,
        website: "https://docs.google.com/document/d/1A6aKL_v3SmM_1A0e5UHHGLdIGr_VvPUG58HuLL-w630/edit#heading=h.e6k2mwzb3580",
        credits: 1,
    },
    {
        department: "PHYS",
        number: "399O",
        title: "Introduction to Computational Fourier Optics",
        advisor: "Thomas Antonsen",
        facilitators: [ 
        { name: 'Benjamin Schreyer', email: 'bschrey1@terpmail.umd.edu' },
        ],
        description: "Computational methods (Fourier Optics) for advanced optical modeling. Implement algorithms in Python3 or MATLAB, focusing on physics and mathematics. Explore experimental considerations and plotting schemes. Simulate telescope or laser cavity systems for understanding and improvement recommendations. Skeleton code provided to allow focus on key calculations and interpretation.",
        id: 212,
        website: "https://docs.google.com/document/d/140PeJMf5MdUUbAhZ3XsdycC9CtL3pfM88gY_ZsvQf2o/edit?usp=sharing",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398L",
        title: "Introduction to Competitive Programming",
        advisor: "Laxman Dhulipala",
        facilitators: [
        { name: 'Cheng-Yuan Lee', email: 'cl571128@terpmail.umd.edu' },
        { name: 'Spencer Lutz', email: 'sjlutz@terpmail.umd.edu' },
        { name: 'Mazin Karjikar', email: 'karjikar@terpmail.umd.edu' },
        ],
        description: "This course covers most of the basic techniques and algorithms that are used in competitive programming. Topics include C++ STL, greedy, dynamic programming, divide and conquer, graph algorithms, and data structures. Students will learn different algorithmic techniques and apply these concepts to solve interesting programming problems in practice. ",
        id: 213,
        website: "https://docs.google.com/document/d/1-N_3blidKxEsXigvoqVYISXVTQJnsrp_YiFLuh93Egg/edit?usp=sharing",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398M",
        title: "Introduction to Product Design with Figma",
        advisor: "Cliff Bakalian",
        facilitators: [
        { name: 'Beatrice Chung', email: 'beachung@terpmail.umd.edu' },
        { name: 'Amber Chen', email: 'achen626@terpmail.umd.edu' },
        ],
        description: "An exploration into the world of Figma! Figma is a popular collaborative design tool used by many developers for brainstorming, proof of concepts and website/application design. We will be exploring the various capabilities of Figma, and how we can create a website or mobile application from a design made on Figma. Students will learn principles of design, create mockups, and build their own website/mobile app that will look great for resumes and portfolios.",
        website: "https://drive.google.com/file/d/1rHug-L4lTAS8ls4BRbzQOvhN_XXgj2bT/view",
        id: 214,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398Q",
        title: "Secure Communication",
        advisor: "Dr. Ian Miers",
        facilitators: [ 
        { name: 'Harikesh Kailad', email: 'emh@terpmail.umd.edu' },
        { name: 'Clarence Lam', email: 'clam1234@terpmail.umd.edu' },
        ],
        description: "Covers basic topics in cryptography and explains how those topics are applied to modern forms of communication. We will cover messaging protocols and modern texting apps such as iMessage, Whatsapp, Signal, and more. We will also discuss ways of communicating with other forms of media such as audio and video. Finally, time-permitting, we will discuss the basics of quantum cryptography, and where current research in that field is headed.",
        website: "https://drive.google.com/file/d/1vytQLSdwc0JFev1acPelDA14h0x23M0j/view",
        id: 215,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398R",
        title: "Binary Exploitation",
        advisor: "Tudor Dumitras",
        facilitators: [ 
        { name: 'Andrei Kotliarov', email: 'akotlia1@umd.edu' },
        { name: 'Edward Feng', email: 'edwfeng@umd.edu' },
        { name: 'Avery Parker', email: 'aparke18@umd.edu' },
        { name: 'Hari Kailad', email: 'emh@umd.edu' },
        ],
        description: "An introduction to exploiting common vulnerabilities in compiled applications. Topics include an overview of C, intro to x86 assembly, buffer overflows on stack and heap, format string bugs, heap exploitation, and other special topics (kernel/browser/blockchain). Students will be able to write exploits for all the bugs learned in class, and secure their own applications.",
    website: "https://drive.google.com/file/d/1s_U3KhpnhmRkqRCR7EYSDUYcac5PW8pm/view",  
        id: 216,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398N",
        advisor: "Elias Gonzalez",
        facilitators: [
        { name: "Logan Stevens", email: "lsteven7@umd.edu" },
        { name: "Anushka Anand", email: "aanand10@terpmail.umd.edu" },
        { name: "Chayanika Sinha", email: "csinha@umd.edu " },
        ],
        description: "This course will introduce students to the different aspects of ethics within Computer Science. There will be 14 different topics, each one focusing on a different issue regarding ethics in the tech industry. Students will learn what to do in these situations, understand how these issues impact society, and participate in in-class discussions about these topics. After taking this course students should be able to recognize these issues in the real world and be able to use their knowledge to try and better the field.",
        id: 217,
        title: "Ethics in Computer Science",
        website: "https://drive.google.com/file/d/1msz8O5hElarvTD2odNvVp6w2qMyAopEQ/view",
        department: "CMSC",
        credits: 1,
    },
    ],
}