export const fall2025 = {
    departments: ["CMSC", "ENAE", "BSCI", "SPHL"],
    classes: [
    {
        department: "CMSC",
        number: "389P",
        advisor: "Huaishu Peng",
        facilitators: [
        { name: "Angelyn Pham", email: "angpham@umd.edu" },
        ],
        description: "Prepares students for PM interviews in the technology industry. The class will be a combination of lectures and in-class activities that will provide hands-on practice for PM roles. We will begin with interview questions involving behavioral and technical concepts, and transition tomore complex PM-specific topics including product design, analytical, and case questions.",
        id: 0,
        title: "Special Topics in Computer Science; Mastering the PM Interview",
        website: null,
        credits: 1,
    },
    {
        department: "ENAE",
        number: "288B",
        advisor: "Dr. Alison Flateau",
        facilitators: [
        { name: "Caleb Becker-Schwartz", email: "calebbs@terpmail.umd.edu" },
        ],
        description: "Failures in Human Spaceflight: Apollo 1, Challenger, & Columbia provides an introduction to fatal accidents in American spaceflight history. Students will study the engineering failures and management decisions leading to each disaster. Additionally, they will consider the investigations, public responses, and impacts prompted by the accidents.Readings will include official accident reports, internal NASAcommunications, and personal accounts. Students will discuss how these disasters shaped modern risk management and what lessons were learned - or ignored - along the way.",
        id: 1,
        title: "Failures in Human Spaceflight: Apollo 1, Challenger, & Columbia",
        website: "",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "CMSC398M",
        advisor: "Clifford Bakalian",
        facilitators: [
        { name: "Amber Chen", email: "achen626@terpmail.umd.edu" },
        { name: "Beatrice Chung", email: "beachung@terpmail.umd.edu" },
        ],
        description: "An exploration into the world of Figma! Figma is a popular collaborative design tool used by many developers for brainstorming, proof of concepts, and website/application design. We will be exploring the various capabilities of Figma, and how we can create a website or mobile application from a design made on Figma. Students will learn principles of design, create mockups, and build their own website/mobile app that will look great for resumes and portfolios.",
        id: 2,
        title: "Special Topics in Computer Science; Introduction to Product Design with Figma",
        website: "",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389L",
        advisor: "Mohammad Teli",
        facilitators: [
        { name: "Samuel Kinstlinger", email: "samkinst@terpmail.umd.edu" },
        { name: "Andrew Xu", email: "andyxu55@terpmail.umd.edu" },
        ],
        description: "This course provides a comprehensive introduction to reinforcement learning. We begin with a review of key concepts in machine learning and planning, such as gradient descent and neural networks. We then explore core reinforcement learning algorithms-including value-based, policy-gradient, and actor-critic methods-along with essential tools like TensorFlow and Gymnasium. The course focuses on applications in robotics and autonomous systems, finance, and games.",
        id: 3,
        title: "Special Topics in Computer Science; Reinforcement Learning",
        website: null,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398P",
        advisor: "Maksym Morawski",
        facilitators: [
        { name: "Suvrath Chivukula", email: "schivuku@terpmail.umd.edu" },
        { name: "Pranav Palle", email: "ppalle1@terpmail.umd.edu" },
        { name: "Amogh Gurram", email: "amogh@terpmail.umd.edu" },
        ],
        description: "This course provides a practical introduction to cloud computing with Amazon Web Services (https://aws.amazon.com/about-aws/) (AWS). Students will learn how to build applications using a variety of AWS services, including S3, EC2, Lambda, and ECS. Additionally they will have an exam ready understanding of many services, benefits, and features of AWS. Thecourse will culminate in a final resume-worthy project that will be built, deployed, and demoed.",
        id: 4,
        title: "Special Topics in Computer Science; Practical Cloud Computing with AWS",
        website: null,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389E",
        advisor: "Cliff Bakalian",
        facilitators: [
        { name: "Amrit Magesh", email: "amagesh@umd.edu" },
        { name: "Minsi Hu", email: null },
        ],
        description: "We will explore the theory and applications of combinational and sequential circuits. All projects will be done using Minecraft Redstone.The course will cover basic gates to more advanced circuits including memory gates and large sequential circuits.",
        id: 5,
        title: "Special Topics in Computer Science; Digital Logic Design Through Minecraft",
        website: "https://cmsc-389e.github.io",
        credits: 0,
    },
    {
        department: "CMSC",
        number: "CMSC398R",
        advisor: "Tudor Dumitras",
        facilitators: [
        { name: "Hari Kailad", email: "emh@terpmail.umd.edu" },
        { name: "Edward Feng", email: "edwfeng@terpmail.umd.edu" },
        ],
        description: "An introduction to exploiting common vulnerabilities in compiled applications. Topics include an overview of C, intro to x86 assembly, buffer overflows on stack and heap, format string bugs, heap exploitation, and other special topics (kernel/browser/blockchain). Students will be able to write exploits for all the bugs learned in class, and secure their own applications.",
        id: 6,
        title: "Special Topics in Computer Science; Binary Exploitation",
        website: null,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389B",
        advisor: "Cliff Bakalian",
        facilitators: [
        { name: "Arwen Ferro", email: "aferro12@umd.edu" },
        { name: "June Cagan", email: "jcagan@umd.edu" },
        { name: "Andrew Wagger", email: "anwagger@terpmail.umd.edu" },
        ],
        description: "A Tour of Programming Languages introduces students to various programming paradigms and languages. This course aims to help students further their understanding of programming language (PL) design, as wellas gain experience with different programming philosophies, paradigms, and mindsets.",
        id: 7,
        title: "Special Topics in Computer Science; A Tour of Programming Languages",
        website: null,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "CMSC398L",
        advisor: "Laxman Dhulipala",
        facilitators: [
        { name: "Vijaykaarti Sundarapandiyan", email: "vsundar1@umd.edu" },
        { name: "Mazin Karjikar", email: "mkarjika@umd.edu" },
        { name: "Max Wang", email: "maxyyw@terpmail.umd.edu" },
        ],
        description: "Covers most of the basic techniques and algorithms that are used in competitive programming. Topics include C++ STL, greedy, dynamic programming, divide and conquer, graph algorithms, and data structures. Students will learn different algorithmic techniques and apply these concepts to solve interesting programming problems in practice.",
        id: 8,
        title: "Special Topics in Computer Science; Introduction to Competitive Programming",
        website: null,
        credits: 0,
    },
    {
        department: "CMSC",
        number: "CMSC388J",
        advisor: "Michael Marsh",
        facilitators: [
        { name: "Lance Uymatiao", email: "lpu@terpmail.umd.edu" },
        { name: "Aryan Thakar", email: "arthakar@terpmail.umd.edu" },
        ],
        description: "Explores tools such as Python, Flask, Django, MongoDB, Svelte, and React.",
        id: 9,
        title: "Special Topics in Computer Science; Building Secure Web Applications",
        website: null,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389O",
        advisor: "Tom Goldstein",
        facilitators: [
            { name: "Hita Thota", email: "hthota27@terpmail.umd.edu" },
            { name: "Andrew Yang", email: "ayang03@terpmail.umd.edu" },
            { name: "Ishan Khillan", email: "ikhillan@terpmail.umd.edu" },
            { name: "Shreyes Vardes", email: "svarde1@terpmail.umd.edu    " },
        ],
        description: "Technical interviewing is a critical skill for acquiring internships and jobs. Students will gain a comprehensive, practical introduction to technical interviews. Students will be introduced to basic topics such as Big O and String Manipulation and later move into more complex topicssuch as Graphs and Dynamic Programming. Most in-class time will bespenton mock interviews to give real interview practice. The course facilitators are experienced in interviewing and have received internship/job offers from companies like Meta, Optiver, Bloomberg, Amazon, Apple, Microsoft, Databricks, Capital One, and more.",
        id: 10,
        title: "Special Topics in Computer Science; The Coding Interview",
        website: null,
        credits: 1,
    },
    {
        department: "BSCI",
        number: "238I",
        advisor: "Dr. Najib M. El-Sayed",
        facilitators: [
            { name: "Anushka Poddar", email: "apoddar2@terpmail.umd.edu" },
            { name: "Aditri Gadigi", email: "agadigi@terpmail.umd.edu" },
        ],
        description: "Introduces students to the fundamental principles of machine learning and its applications in biology and medicine. Students will learn about key machine learning techniques, including classification, regression, clustering, and deep learning, with a focus on practical applications like cancer diagnosis, gene expression analysis, and protein structure prediction. Through lectures and guided projects, students will gain an understanding of how to apply machine learning models to biological datasets, evaluate their performance, and interpret results. No prior programming or machine learning experience is required.",
        id: 11,
        title: "Special Topics in Biology Student Initiated Courses; Machine Learning for the Life Sciences",
        website: null,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398W",
        advisor: "Christopher Kauffman",
        facilitators: [
            { name: "Karan Jain", email: "kjain12@terpmail.umd.edu" },  
            { name: "Mohmmad Durrani", email: null },
        ],
        description: "This course will provide a broad overview of many common and useful tools, like the command line, Git, debuggers, build systems, and more. Through a hands-on approach, you will be introduced to a variety of tools and techniques that can immediately be applied to everyday problems. We aim to provide students with material that improves their computing ecosystem literacy and increases their efficiency as a developer.",
        id: 12,
        title: "Practical Tools for Efficient Development",
        website: null,
        credits: 1,
    },
    {
        // The spreadsheet says this is supposed to be under BUFN, but it's under BMGT on testudo
        department: "BMGT",
        number: "299D",
        advisor: "Albert S. Kyle",
        facilitators: [
        { name: "Somil Varshney", email: "somilv@umd.edu" },
        ],
        description: "This course equips students with essential financial skills to navigate real-world money matters with confidence. Covering budgeting, investing, taxes, credit cards, retirement savings, and more, students will learn how to make informed financial decisions that set them up for long-term success. Through practical exercises and current real-world examples, this course provides a solid foundation in personal finance. No prior financial knowledge is required.",
        id: 13,
        title: "Student Initiated Special Topics; Introduction to Practical Financial Literacy",
        website: null,
        credits: 1,
    },
    {
        department: "SPHL",
        number: "276",
        title: "Decolonizing Medicine: Steps to Actionable Change",
        advisor: "Dina Borzekowski",
        facilitators: [
        { name: 'Anya Tahi', email: 'atahi@terpmail.umd.edu' },
        { name: 'Aliza Zulfiqar', email: 'aliza4@terpmail.umd.edu' },
        ],
        description: "This course provides a comprehensive foundation of how colonial legacies continue to shape global health systems and medical practices. We will critically engage with the concept of 'the White body' as the standard in medical training, explore the consequences of the historical context underpinning colonial medicine, and interrogate neocolonial dynamics in contemporary global health efforts. Designed for students interested in careers in medicine, public health, or health policy, this course will challenge students to rethink the ethical and epistemological frameworks that underlie modern healthcare.",
        website: "https://drive.google.com/file/d/1vtsaYEFbFtKjIHP8QWdjfLripevG5IOk/view?usp=sharing",
        id: 14,
        credits: 1,
    },
    ]
}
