
export const fall2026 =
{
    departments: ["CMSC", "MATH", "BSCI", "CHIN", "SLLC", "ENAE"],
    classes: [
    {
        department: "CMSC",
        number: "389L",
        title: "Reinforcement Learning",
        advisor: "Mohammad Nayeem Teli",
        facilitators: [
        { name: 'Samuel Kinstlinger', email: 'samkinst@terpmail.umd.edu' },
        { name: 'Andrew Xu', email: 'andyxu55@terpmail.umd.edu' },
        { name: 'Brian Fugh', email: 'bfugh@terpmail.umd.edu' },
        ],
        description: "This course provides a comprehensive introduction to reinforcement learning. We begin with a review of key concepts in machine learning and planning, such as gradient descent and neural networks. We then explore core reinforcement learning algorithms—including value-based, policy-gradient, and actor-critic methods—along with essential tools like TensorFlow and Gymnasium. The course focuses on applications in robotics and autonomous systems, finance, and games.",
        website: "https://drive.google.com/file/d/1_QXJMnXaafNSBBLsmwNpfPTheBKss_VK/view",
        id: 301,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "388J",
        title: "Building Secure Web Applications",
        advisor: "Michael Marsh",
        facilitators: [
        { name: 'Rushil Juneja', email: 'rushilj@terpmail.umd.edu' },
        { name: 'Roshan Aterugu', email: 'roshana@terpmail.umd.edu' },
        ],
        description: "This course is an introduction to building full-stack applications with Python and Flask. We'll start with the basics of building web apps with Python and Flask, then transition to user and database management with MongoDB. Then, we'll go into other topics, and finish by showing you how to deploy your web app with Vercel. You'll end the class with a final project where you build and deploy your own Flask application from scratch.",
        website: "https://vercel-iota-flax.vercel.app/388j",
        id: 302,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389O",
        title: "The Coding Interview",
        advisor: "Tom Goldstein",
        facilitators: [
        { name: 'Hita Thota', email: 'hthota27@terpmail.umd.edu' },
        { name: 'Cathy Wu', email: 'swu312@terpmail.umd.edu' },
        { name: 'Jude Lwin', email: 'judelwin@umd.edu' },
        ],
        description: "This course provides a comprehensive, practical introduction to technical interviews. The course will start with basic topics such as Big O and String Manipulation. We will then move into more complex topics such as Graphs and Dynamic Programming. Most of the classes will be in-class interviews to give real interview practice.",
        website: "https://docs.google.com/document/d/1sotPYc4aMkA_JWafrLm7kMgD96Rw4eaOeIGxMBg6A-8/edit?tab=t.0#heading=h.9bydr0enr5nw",
        id: 303,
        credits: 1,
    },
    {
        department: "MATH",
        number: "299P",
        title: "Advanced Poker Theory",
        advisor: "William Gasarch",
        facilitators: [
        { name: 'Oliver Andrews', email: 'oandrew1@terpmail.umd.edu' },
        ],
        description: "This course explores the mathematical and strategic foundations of No Limit Texas Hold'em (NLH) (and other games) through the lens of probability, expected value, and game theory. Basic rules and gameplay structure will be introduced briefly to support subsequent mathematical modeling and analysis. The course emphasizes reasoning and structured analysis rather than playing ability, and students will learn to justify strategic decisions using mathematical models and logical argumentation. The course will also introduce computational approaches to strategy analysis, including Monte Carlo simulation for estimating hand equity. By the end of the semester, students will understand how equilibrium strategies emerge in imperfect information games and will be able to analyze complex poker scenarios using principles that underlie modern Game Theory Optimal (GTO) strategy. While No Limit Texas Hold'em serves as the primary case study, the probabilistic and game-theoretic techniques covered apply broadly to other card games, board games, and strategic decision-making problems more generally.",
        website: "https://drive.google.com/file/d/11dZdedfbhksXmQyenFuQYaOgFKVpEaBY/view",
        id: 304,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389E",
        title: "Digital Logic Design Through Minecraft",
        advisor: "Cliff Bakalian",
        facilitators: [
        { name: 'Esther Yu', email: 'eyu50207@terpmail.umd.edu' },
        { name: 'Silas Rager', email: 'srager@terpmail.umd.edu' },
        { name: 'Grace Yang', email: 'gyang128@terpmail.umd.edu' },
        ],
        description: "In this class, we will explore the theory and applications of combinational and sequential circuits. All projects will be done using Minecraft Redstone. The course will cover basic gates to more advanced circuits including memory gates and large sequential circuits. The first half of the class will focus on combinational logic gates, and the second half will introduce time-based sequential circuits. The basic course structure consists of one class per week of theory and demonstration, followed by a project due every other week that applies that theory. Projects are cumulative/iterative and will build upon each other. The class is purely project based, with 5 projects and a single final project.",
        website: "https://www.overleaf.com/project/69b32c4bf1c9f8e33a906196",
        id: 305,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398M",
        title: "Introduction to Product Design with Figma",
        advisor: "Cliff Bakalian",
        facilitators: [
        { name: 'Purva Jani', email: 'pjani26@terpmail.umd.edu' },
        { name: 'Olivia Zhang', email: 'ozhang1@terpmail.umd.edu' },
        ],
        description: "An exploration into the world of Figma! Figma is a popular collaborative design tool used by many developers for brainstorming, proof of concepts, and website/application design. In this course, we will be exploring the various capabilities of Figma, and how we can create a website or mobile application from a design made on Figma. Students will learn principles of design, create mockups, and build their own website/mobile app that will look great for resumes and portfolios.",
        website: "https://drive.google.com/file/d/1-ljWLYfPwltV_4ZkwCVkpTuI7eLcWLaO/view",
        id: 306,
        credits: 1,
    },
    {
        // this cant be found on testudo. confirm with Alan Sussman and facilitators whether this course is actually taught.
        department: "CMSC",
        number: "398A",
        title: "Developing Full Stack Applications with AI",
        advisor: "Alan Sussman",
        facilitators: [
        { name: 'Adam Zeineldin', email: 'azeineld@terpmail.umd.edu' },
        { name: 'Dvij Raicha', email: 'draicha@terpmail.umd.edu' },
        ],
        description: "This course introduces students to building real-world software projects using modern AI-assisted development tools. Students will learn how to effectively prompt large language models, use AI coding assistants such as Cursor and Copilot, and integrate AI throughout the software development lifecycle—from prototyping and frontend development to backend systems, debugging, testing, and deployment. Emphasis is placed on responsible and efficient AI usage, understanding the limitations of AI-generated code, and developing engineering judgment when working with automated tools. By the end of the course, students will have collaboratively designed, built, and deployed a complete application, demonstrating both technical proficiency and thoughtful use of AI as a development aid.",
        website: "https://docs.google.com/document/d/1sDiTY2zXELl2IL8QSgCmSxlbwX4SAx8_8DkVrHS9llU/edit?tab=t.0#heading=h.e6k2mwzb3580",
        id: 307,
        credits: 1,
    },
    {
        department: "CHIN",
        number: "219A",
        title: "Why Taiwan Matters",
        advisor: "Minglang Zhou",
        facilitators: [
        { name: 'Cecelia Clanton', email: 'cclanton@umd.edu' },
        ],
        description: "This course introduces students to Taiwan's history, culture, political development, and global significance. Through a combination of historical and contemporary analysis, students will explore Taiwan's evolution into a democratic society, its complex relationship with China, its strategic ties with the United States, and its central role in the global semiconductor industry. The course also considers questions of identity and culture to better understand Taiwan's place in the world today.",
        website: "https://docs.google.com/document/d/1-GIYUGYNkL_1oNHlaq5ytX6TpNNqLP3ebigrnMffR6g/edit?tab=t.0#heading=h.e6k2mwzb3580",
        id: 308,
        credits: 1,
    },
    {
        // facilitators and advisor are still TBA — confirm with class
        // coordinator whether this course is actually running before publishing.
        department: "BSCI",
        number: "238J",
        title: "Network Science in Biological Systems",
        advisor: "TBA",
        facilitators: [
        { name: 'TBA', email: '' },
        ],
        description: "This course is an introduction to topics like network science and graph R programming and additional tools. Students will then explore applications of network science in topics like understanding dynamic neural networks and how disruptions in these networks can relate to neurological diseases. Students are not required to have prior experience with programming; the course includes guided tutorials to develop students' skills for future academic and career experiences.",
        website: "",
        id: 309,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398N",
        title: "Ethics in the Age of AI",
        advisor: "Elias Gonzales",
        facilitators: [
        { name: 'Aryan Thakar', email: 'arthakar@umd.edu' },
        { name: 'Arshnoor Bhutani', email: 'arshnoor@terpmail.umd.edu' },
        ],
        description: "We are excited to reintroduce CMSC 389N, formerly Ethics in Computer Science, now rebranded as Ethics in the Age of AI. This rebranding reflects a deliberate shift in focus, a shift that mirrors where the world is heading. Artificial intelligence is embedded in hiring pipelines, healthcare diagnostics, criminal justice, and financial systems. The decisions these systems make affect real people, often in ways that are invisible and difficult to reverse. CMSC 389N is designed to bring these decisions and choices to light. Through a blend of philosophical inquiry and technical practice, students will apply ethical frameworks to real-world AI dilemmas while engaging in hands-on work with fairness tools, interpretability methods, and red-teaming large language models. The overarching goal of this re-designed course is to help students develop the ability to critically analyze the ethical implications of AI systems, propose technically sound solutions to ethical problems, understand the mechanism of bias in algorithms, and make informed judgments about whether and how AI technologies should be designed and deployed.",
        website: "https://drive.google.com/file/d/1gvazVxmV746LbD102G3nUVllje3wvY4v/view",
        id: 310,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398P",
        title: "Practical Cloud Computing with AWS",
        advisor: "Maksym Morawski",
        facilitators: [
        { name: 'Suvrath Chivukula', email: 'schivuku@terpmail.umd.edu' },
        { name: 'Shivank Bhimavarpu', email: 'sbhima@terpmail.umd.edu' },
        { name: 'Max Yang', email: 'myang27@terpmail.umd.edu' },
        ],
        description: "This course provides a practical introduction to cloud computing with Amazon Web Services (AWS). Students will learn how to build applications using a variety of AWS services, including S3, EC2, Lambda, and ECS. Additionally they will have an exam ready understanding of many services, benefits, and features of AWS. The course will culminate in a final resume-worthy project that will be built, deployed, and demoed.",
        website: "https://docs.google.com/document/d/10X4xqa4sHSWa8rKLf4u9LZt2L3XQtkgCrxH1X7fQOKQ/edit?tab=t.0#heading=h.bpgj4w80t632",
        id: 311,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389P",
        title: "Mastering the PM Interview",
        advisor: "Herve Franceschi",
        facilitators: [
        { name: 'Stacy Sun', email: 'ssun24@terpmail.umd.edu' },
        { name: 'Ayush Dewagan', email: 'adewagan@terpmail.umd.edu' },
        ],
        description: "Our course is geared towards getting students ready for PM interviews in the technology industry. The class will be a combination of lectures and in-class activities that will provide hands-on practice for PM roles. We will begin with interview questions involving behavioral and technical concepts, and transition to more complex PM-specific topics including product design, analytical, and case questions.",
        website: "https://drive.google.com/file/d/1xYAIaeUJO5MDuRrTqXGetYLa-1gRNGAI/view",
        id: 312,
        credits: 1,
    },
    {
        department: "SLLC",
        number: "118A",
        title: "Introductory Spoken Sanskrit",
        advisor: "Sean Pue",
        facilitators: [
        { name: 'Niva Mangalampalli', email: 'nmangala@terpmail.umd.edu' },
        ],
        description: "What if you could engage in a classical language, by not only reading, but by learning how to speak the language? This 1-credit introductory course offers an immersive and engaging approach to spoken Sanskrit, with an emphasis on building practical conversational skills from the very first class. Through interactive dialogues, guided practice, and dynamic activities, students will develop a foundation in essential vocabulary, clear pronunciation, and simple grammatical structures. The course prioritizes active use over memorization, encouraging students to think and communicate naturally in Sanskrit. By the end of the course, students will be able to understand and participate in basic conversations, gaining both confidence in speaking and a deeper connection to the language's rich classical heritage.",
        website: "https://drive.google.com/file/d/1saIcnVCB8TRzVmiAS_ZMtAzh7PH3MjDs/view",
        id: 313,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398L",
        title: "Introduction to Competitive Programming",
        advisor: "Laxman J Dhulipala",
        facilitators: [
        { name: 'Anirudh Duddebanda', email: 'adudde@terpmail.umd.edu' },
        { name: 'Arnav Srivastava', email: 'asrivas8@terpmail.umd.edu' },
        { name: 'Matthew Chen', email: 'mc3297@terpmail.umd.edu' },
        ],
        description: "This course covers most of the basic techniques and algorithms that are used in competitive programming. Topics include C++ STL, greedy, dynamic programming, divide and conquer, graph algorithms, and data structures. Students will learn different algorithmic techniques and apply these concepts to solve interesting programming problems in practice.",
        website: "https://docs.google.com/document/d/1vBeEJDiP8KlL-nM2hUWhEkEyg4j6jTOwIYz-UhbqORA/edit?tab=t.0#heading=h.e6k2mwzb3580",
        id: 314,
        credits: 1,
    },
    {
        department: "BSCI",
        number: "238I",
        title: "Machine Learning for the Life Sciences",
        advisor: "Najib El-Sayed",
        facilitators: [
        { name: 'Anushka Poddar', email: 'apoddar2@terpmail.umd.edu' },
        { name: 'Aditri Gadigi', email: 'agadigi@terpmail.umd.edu' },
        ],
        description: "Machine learning is transforming the life sciences, enabling breakthroughs in fields such as genomics, medical imaging, and drug discovery. This course introduces students to the fundamental principles of machine learning and its applications in biology and medicine. Students will learn about key machine learning techniques, including classification, regression, clustering, and deep learning, with a focus on practical applications like cancer diagnosis, gene expression analysis, and protein structure prediction. Through lectures and guided projects, students will gain an understanding of how to apply machine learning models to biological datasets, evaluate their performance, and interpret results. No prior programming or machine learning experience is required—this course is designed to bridge the gap between computational techniques and life science research, preparing biology students to understand and leverage machine learning as a tool as they encounter real-world challenges in their fields of study.",
        website: "https://docs.google.com/document/d/1myUKJyDyNS6BszgSkkXggmUsfozHZ_rn9DHbfOugH4Q/edit?tab=t.0#heading=h.e6k2mwzb3580",
        id: 315,
        credits: 1,
    },
    {
        // update the website and advisor/facilitators once confirmed by class coordinator
        department: "ENAE",
        number: "288B",
        title: "Failures in Human Spaceflight",
        advisor: "Alison Flatau",
        facilitators: [
        { name: 'Caleb Becker-Schwartz', email: '' },
        ],
        description: "Failures in Human Spaceflight: Apollo 1, Challenger, & Columbia provides an introduction to fatal accidents in American spaceflight history. Students will study the engineering failures and management decisions leading to each disaster. Additionally, they will consider the investigations, public responses, and impacts prompted by the accidents. Readings will include official accident reports, internal NASA communications, and personal accounts. Students will discuss how these disasters shaped modern risk management and what lessons were learned - or ignored - along the way.",
        website: "",
        id: 316,
        credits: 1,
    },
    ]
}