export const spring2026 =
{
    departments: ["CMSC", "ASTR", "BSCI", "MATH", "SPHL", "JOUR", "PLCY", "RUSS"],
    classes: [
    {
        department: "ASTR",
        number: "288T",
        title: "Introduction to Astrophotography",
        advisor: "Elizabeth Warner",
        facilitators: [
        { name: 'Matthew Prem', email: 'mprem@terpmail.umd.edu' },
	{ name: 'Paul Voelker', email: 'pvoelker@terpmail.umd.edu' },
        ],
        description: "In this course, you will learn the foundations of several popular forms of amateur astrophotography, along the way gaining practical astronomy knowledge which you can apply in your free time, no matter what career you pursue.By the end of this course, you will know important regions of the night sky, how to photograph a wide variety of celestial objects, and how to view and analyze astro images taken from professional sources.",
        website: "https://drive.google.com/file/d/1uhk8dtyCHOR0Sp84h2MwYhsyLepV9R6d/view",
        id: 219,
        credits: 1,
    },
    {
        department: "BSCI",
        number: "238A",
        title: "Ornithology",
        advisor: "Daniel Gruner",
        facilitators: [
        { name: 'Joshua Lucas Johnson', email: 'jljohns@terpmail.umd.edu' },
        ],
        description: "Introduction into bird identification, biology, and ecology. Through readings, multimedia, lectures, discussions, and field trips, we will learn to identify birds of the region, along with their systematics, evolution, and behavior.",
        website: "https://drive.google.com/file/d/1DSuuzBZR1mlR-UO2SIwBIcYJKjiawMJd/view",
        id: 219,
        credits: 1,
    },
    {
        department: "BSCI",
        number: "238I",
        advisor: "Dr. Najib M. El-Sayed",
        facilitators: [
            { name: "Anushka Poddar", email: "apoddar2@terpmail.umd.edu" },
            { name: "Aditri Gadigi", email: "agadigi@terpmail.umd.edu" },
        ],
        description: "Introduces students to the fundamental principles of machine learning and its applications in biology and medicine. Students will learn about key machine learning techniques, including classification, regression, clustering, and deep learning, with a focus on practical applications like cancer diagnosis, gene expression analysis, and protein structure prediction. Through lectures and guided projects, students will gain an understanding of how to apply machine learning models to biological datasets, evaluate their performance, and interpret results. No prior programming or machine learning experience is required.",
        id: 11,
        title: "Machine Learning for the Life Sciences",
        website: "https://docs.google.com/document/d/1gsGnULfoaxWqq6rq35GmRe4hjkTVkUbZyEbhpxBIyXA/edit?tab=t.0#heading=h.e6k2mwzb3580",
        credits: 1,
    },
    {
        department: "JOUR",
        number: "288T",
        title: "Building Newsroom-Wide Tools with Artificial Intelligence",
        advisor: "Derek Willis",
        facilitators: [
        { name: 'Apurva Mahajan', email: 'amahaja@umd.edu' },
        ],
        description: "This course will introduce students to how they can use AI coding assistants to automate newsroom processes and most importantly, make reporters' day-to-day lives easier! These skills can be applied to everyday newsroom tasks such as sourcing data, maintaining complex databases, managing story tips, tracking coverage and analyzing content.",
        website: "https://drive.google.com/file/d/1JvD0sCbfZwvrfVNx7gz7ZPKtUP0Qy3Et/view?usp=sharing",
        id: 219,
        credits: 1,
    },
    {
        department: "MATH",
        number: "299G",
        title: "Proofs from The Book",
        advisor: "William Gasarch",
        facilitators: [
        { name: 'Kelin Zhu', email: 'kelinzhu@terpmail.umd.edu' },
	{ name: 'Daniel Yuan', email: '' },
        ],
        description: "We aim to illustrate basic ideas of Combinatorics by exploring elementary proofs of theorems with great historical significance. The focus is on exposure to, and appreciation of, classic examples rather than applying combinatorial techniques. The proofs we discuss are so beautiful that Paul Erdos once said they are from “The Book” - God’s book of the most elegant proof of each theorem.",
        website: "https://files.catbox.moe/igo577.pdf",
        id: 220,
        credits: 1,
    },
    {
        department: "PLCY",
        number: "299G",
        title: "Public Discourse and Effective Advocacy in SGA",
        advisor: "Toby Egan",
        facilitators: [
        { name: 'Taryn Reinhart', email: 'tarynr12@umd.edu' },
        ],
        description: "A course aimed at educating the elected and appointed officials in SGA on how to effectively govern-in both student and broader contexts-through providing background on theories of productive governments. The other aspect of this course will be to better understand public discourse through experiential learning via the SGA's committee and General Body Meeting (GBM) structure.",
        website: "https://files.catbox.moe/igo577.pdf",
        id: 220,
        credits: 1,
    },
    {
        department: "RUSS",
        number: "299A",
        title: "Russian Cultural Norms",
        advisor: Michael Lavery",
        facilitators: [
        { name: 'Vasiley Syomin', email: 'tarynr12@umd.edu' },
	{ name: 'Andrew Makarevich', email: 'amakarev@terpmail.umd.edu' },
        ],
        description: "This one-credit, low-stakes Russian conversation course is designed for students with a foundation in Russian grammar, which may include both heritage speakers and language learners seeking to strengthen theirspeaking confidence. Through discussions conducted in Russian, students will explore cultural norms and modern expressions of Russian identity across music, film, internet culture, and everyday life. By examining popular media, social customs, humor, and communication styles, studentswill gain insight into how Russians interpret and express the world around them. The course emphasizes conversation, cultural understanding,and real-world language use, helping students connect linguistic knowledge with authentic cultural context.",
        website: "https://docs.google.com/document/d/1rBsM9kB8PuOEWeJrkamm79GDdmj7fPwLmAVesJX9Xzw/edit?tab=t.0",
        id: 220,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389Y",
        title: "Open Source Intelligence (OSINT)",
        advisor: "Dave Levin",
        facilitators: [
        { name: 'Alexander Zuzin', email: 'azyuzin@terpmail.umd.edu' },
        ],
        description: "This course teaches you to find and analyze publicly available information while protecting your own digital footprint. You'll master both offensive reconnaissance techniques and defensive counter-intelligence strategies. The curriculum covers Python automation, developing AI-powered analysis tools, dark web intelligence, satellite imagery analysis, and advanced privacy operations.",
        website: "https://drive.google.com/file/d/1LGk4s8lvorIYe4OZX1iWy0QV7TlD3z0J/view",
        id: 222,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398P",
        advisor: "Maksym Morawski",
        facilitators: [
        { name: "Suvrath Chivukula", email: "schivuku@terpmail.umd.edu" },
        { name: "Pranav Palle", email: "ppalle1@terpmail.umd.edu" },
        { name: "Amogh Gurram", email: "amogh@terpmail.umd.edu" },
        ],
        description: "This course provides a practical introduction to cloud computing with Amazon Web Services (https://aws.amazon.com/about-aws/) (AWS). Students will learn how to build applications using a variety of AWS services, including S3, EC2, Lambda, and ECS. Additionally they will have an exam ready understanding of many services, benefits, and features of AWS. Thecourse will culminate in a final resume-worthy project that will be built, deployed, and demoed.",
        id: 4,
        title: "Practical Cloud Computing with AWS",
        website: "https://docs.google.com/document/d/1RfPVP9fVbkoCgeR5WVRw90yExwog_kTZWyx7kzsO7fc/edit?usp=sharing",
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398L",
        title: "Introduction to Competitive Programming",
        advisor: "Laxman Dhulipala",
        facilitators: [
        { name: 'Mazin Karjikar', email: 'mkarjika@umd.edu' },
        { name: "Max Wang", email: "maxyyw@terpmail.umd.edu"}
        ],
        description: "This course covers most of the basic techniques and algorithms that are used in competitive programming. Topics include C++ STL, greedy, dynamic programming, divide and conquer, graph algorithms, and data structures. Students will learn different algorithmic techniques and apply these concepts to solve interesting programming problems in practice.",
        website: "https://docs.google.com/document/d/1mJ725dm6ZourBay9eKqaA-dm4wE2tNUfuhHWNv2ADfY/edit?usp=sharing",
        id: 222,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389X",
        title: " Advanced Type Systems",
        advisor: "Leonidas Lampropoulos",
        facilitators: [
        { name: 'Sai Divvela', email: 'sdivvela@terpmail.umd.edu' },
        { name: "Finn Voichick", email: "finn@umd.edu"}
        ],
        description: "Ever wonder what the deal about type systems is all about? Why are they helpful, and why should you care about them? In this course, we will survey the field of type theory, and explore the multitude of topics within. This course will focus on providing a high level survey, with anemphasis on intuitive understanding rather than technical details.",
        website: "",
        id: 222,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389P",
        title: "Mastering the PM Interview",
        advisor: "Huaishu Peng",
        facilitators: [
        { name: 'Anthony Ma', email: 'ama8@terpmail.umd.edu' },
        { name: 'Stacy Sun', email: 'ssun24@terpmail.umd.edu' },
        ],
        description: "Product Management is an interesting intersection of technology and business that students are given the opportunity to learn more about in this class. Students are introduced to the tools, techniques, and resources to nail their PM (Product Management) interviews. We'll be providing hands-on practice with PM specific topics including product design, analytical, and case questions. By the end of the class, you should be acing all your PM interviews!",
        website: "https://drive.google.com/file/d/1lu5WdZvs9gRke6Dr5e3IKhBf7UeH7-oe/view?usp=sharing",
        id: 223,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389E",
        title: "Digital Logic Design through Minecraft",
        advisor: "Cliff Bakalian",
        facilitators: [
        { name: 'Amrit Magesh', email: 'amagesh@umd.edu' },
        { name: 'Minsi Hu', email: 'mhu0315@umd.edu' },
        ],
        description: "Explores the fundamentals of digital logic design using Minecraft's Redstone. Using the low-level and intuitive visualization of circuitry Redstone provides, you will create a series of projects that apply principles of digital logic design learned in class.",
        website: "https://drive.google.com/file/d/1Y8hKS0gSPbsEfGSNqXsgeXOIX12NFmtb/view?usp=sharing",
        id: 224,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398M",
        title: "Introduction to Product Design with Figma",
        advisor: "Clifford Bakalian",
        facilitators: [
        { name: 'Beatrice Chung', email: 'beachung@terpmail.umd.edu' },
        { name: 'Purva Jani', email: 'pjani26@terpmail.umd.edu ' },
        ],
        description: "An exploration into the world of Figma! Figma is a popular collaborative design tool used by many developers for brainstorming, proof of concepts, and website/application design. In this course, we will be exploring the various capabilities of Figma, and how we can create a website or mobile application from a design made on Figma. Students will learn principles of design, create mockups, and build their own website/mobile app that will look great for resumes and portfolios. ",
        website: "https://docs.google.com/document/d/1MBVWkx5uRfZOV5Jo2kaezuXdrEzMIp9_6-bfm8R2yPA/edit?usp=sharing",
        id: 225,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "398W",
        title: "Practical Tools for Efficient Development",
        advisor: "Christopher Kauffman",
        facilitators: [
        { name: 'Karan Jain', email: 'kjain12@terpmail.umd.edu' },
        { name: 'Mohammad Durrani', email: 'durranim@terpmail.umd.edu' },
        ],
        description: "Provides a broad overview of many common and useful tools, like the command line, Git, debuggers, build systems, and more. Through a hands-on approach, you will be introduced to a variety of tools and techniques that can immediately be applied to everyday problems. We aim to provide students with material that improves their computing ecosystem literacy and increases their efficiency as a developer.",
        website: "https://drive.google.com/file/d/1qtb4j0jYInZdhFj65HTV8zsQOQuzWcn2/view?usp=sharing",
        id: 227,
        credits: 1,
    },
    {
        department: "CMSC",
        number: "389O",
        title: "The Coding Interview",
        advisor: "Tom Goldstein",
        facilitators: [
        { name: 'Hita Thota', email: 'hthota27@terpmail.umd.edu' },
        { name: 'Ishan Khillan', email: 'ikhillan@terpmail.umd.edu' },
        { name: 'Anirudha Kumar', email: 'akumar33@terpmail.umd.edu' },
        { name: 'Andrew Yang', email: 'ayang03@terpmail.umd.edu' },
        { name: 'Yash Sakharkar', email: 'ysakhark@terpmail.umd.edu' },
        { name: 'Jay Kammula', email: 'jkammula@terpmail.umd.edu' },
        { name: 'Soham Chawathe', email: 'smchawat@terpmail.umd.edu' },
        { name: 'Cathy Wu', email: 'emanbau@terpmail.umd.edu' },
        { name: 'Harshil Chava', email: 'hchava@terpmail.umd.edu' },
        ],
        description: "Technical interviewing is a critical skill for acquiring internships and jobs. Students will gain a comprehensive, practical introduction to technical interviews. Students will be introduced to basic topics such as Big O and String Manipulation and later move into more complex topics such as Graphs and Dynamic Programming. Most in-class time will be spent on mock interviews to give real interview practice. The course facilitators are experienced in interviewing and have received internship/job offers from companies like Meta, Optiver, Bloomberg, Amazon, Apple, Microsoft, Databricks, Capital One, and more.",
        website: "https://docs.google.com/document/d/12fteNfBKtspMCWkLRBN38bI4dCZOWGYCSIbo3FDWGx4/edit?usp=sharing",
        id: 230,
        credits: 1,
    },
    {
        department: "SPHL",
        number: "276",
        title: "Decolonizing Medicine: Steps to Actionable Change",
        advisor: "Dina Borzekowski",
        facilitators: [
        { name: 'Anya Tahi', email: 'atahi@terpmail.umd.edu' },
        { name: 'Aliza Zulfiqar', email: 'aliza4@terpmail.umd.edu' },
        ],
        description: "This course provides a comprehensive foundation of how colonial legacies continue to shape global health systems and medical practices. We will critically engage with the concept of 'the White body' as the standard in medical training, explore the consequences of the historical context underpinning colonial medicine, and interrogate neocolonial dynamics in contemporary global health efforts. Designed for students interested in careers in medicine, public health, or health policy, this course will challenge students to rethink the ethical and epistemological frameworks that underlie modern healthcare.",
        website: "https://docs.google.com/document/d/1-Za8ayy-Iz8Z-9sUstlXk4hiTp8Jkf05wr4O8Lf_U3Q/edit?usp=sharing",
        id: 14,
        credits: 2,
    },

    /*
    {
        department: "DEPT",
        number: "NUMBER",
        title: "TITLE",
        advisor: "ADVISOR",
        facilitators: [ 
        { name: 'FACILITATOR', email: 'EMAIL' },
        { name: 'FACILITATOR', email: 'EMAIL' },
        ],
        description: "DESCRIPTION",
        website: "SYLLABUS",
        id: ID,
        credits: 1,
    },
    */
    ]
}