export const spring2019 = {
    departments: ["CMSC"],
    classes: [
    {
        id: 42,
        department: "CMSC",
        number: "388D",
        title: "2D Game Engine Design",
        facilitators: [
        { name: "Sina Mirnejad", email: "smirneja@terpmail.umd.edu" },
        { name: "Saadiq Shaik", email: "saadiqks@gmail.com" },
        ],
        advisor: "David Mount",
        credits: 1,
        description: "This course will provide basic insight into the design process of a Java game engine, 2D graphics, and the mathematics behind it. The primary focus of the course will be on 2D game engines but will discuss ideas relevant to 3D environments.",
        syllabus: "./assets/syllabi/S19/CMSC388D_S19.pdf",
        website: null,
    },
    {
        id: 44,
        department: "CMSC",
        number: "389C",
        title: "Bitcoin and Other Cryptocurrencies",
        facilitators: [{ name: "Cameron Payton", email: "cpayton@umd.edu" }],
        advisor: "Jonathan Katz",
        credits: 1,
        description:
        "This course provides a comprehensive, practical introduction to the technology behind cryptocur rency and the economy surrounding it. This course will have a heavy emphasis on Bitcoin, but will dive into other types of cryptocurrency as well, such as Ethereum. This course is primarily intended to focus on the technological aspect of cryptocurrency, but we will also spend time discussing the economics of cryptocurrency.",
        syllabus: null,
        website: null,
    },
    {
        id: 45,
        department: "CMSC",
        number: "389K",
        title: "Full-stack Web Development with Node.js",
        facilitators: [
        { name: "Benny Cheng", email: "bcheng1996@gmail.com" },
        { name: "Chirag Shankar", email: "chishankar@gmail.com" },
        { name: "Camille Stacho", email: "camstach@gmail.com" },
        { name: "Chidi Udeze", email: "chidiu98@gmail.com" },
        ],
        advisor: "John Dickerson",
        credits: 1,
        description:
        "This course provides a comprehens ive, practical introduction to modern full-stack web development using JavaScript and Node.js. The course will start with basic HTML/CSS/JavScr ipt. Then, we will move into Node.js and learn how to deploy a website from there. We will learn about Express.js (server-side development modu le) and MongoDB (database) in order to create a complete web application.",
        syllabus: "https://github.com/UMD-CS-STICs/389Kspring19",
        website: null,
    },
    {
        id: 46,
        department: "CMSC",
        number: "389O",
        title: "The Coding Interview",
        facilitators: [
        { name: "Maria McCulley", email: "mmccull2@umd.edu" },
        { name: "Blue Keleher", email: "keleherblue@gmail.com" },
        { name: "Katherine Chase", email: "katherine.m.chase@gmail.com" },
        { name: "George Tong", email: "gjtong@umd.edu" },
        { name: "Kusal De Alwis", email: "kdealwis@umd.edu" },
        { name: "Dhruv Mehta", email: "dhruvnm2@gmail.com" },
        { name: "Atharva Bhat", email: "abhat98@gmail.com" },
        { name: "Nelson Le", email: "nle@umd.edu" },
        { name: "Tim Chen", email: "hello@timothychen.me" },
        ],
        advisor: "Thomas Goldstein",
        credits: 1,
        description:
        'Students will be provided with a comprehensive, practical introduction to technical interviews. Starting with basic topics such as Big O and String Manipulation. We will then move into more complex topics such as Bit Manipulation and Dynamic Programming. Most of the classes will be "In-Class Interviews" and take-home assignments will simulate real interview settings.',
        syllabus: "./assets/syllabi/S19/CMSC389O_S19.pdf",
        website: null,
    },
    {
        id: 47,
        department: "CMSC",
        number: "388F",
        title: "Functional Pearls",
        facilitators: [
        { name: "Cameron Moy", email: "camoy@cs.umd.edu" },
        { name: "Ben Mariano", email: "benmar@cs.umd.edu" },
        ],
        advisor: "David Van Horn",
        credits: 1,
        description:
        "This course will explore elegant examples of functional programming. The first half will provide an introduction to Haskell and four important abstractions: monoids, functors, applicative functors, and monads. We will focus on simple and plentiful examples. The second half will cover a wide variety of functional programming techniques and applications.",
        syllabus: "./assets/syllabi/S19/CMSC388F_S19.pdf",
        website: null,
    },
    {
        id: 48,
        department: "IDEA",
        number: "258D",
        title: "Explorations in Design",
        facilitators: [{ name: "Tianxin Chen", email: "chen128@umd.edu" }],
        advisor: "Meenu Singh",
        credits: 1,
        description:
        "Explorations in Design will give students the opportunity to apply their unique backgrounds to the realm of design. Students will engage in hands-on learning with real clients from various industries. We will explore how good and bad design plays a role in our everyday lives, from the way we order coffee to the logos you see to the signs that help you navigate (or get lost on) the metro.",
        syllabus: "./assets/syllabi/S19/IDEA258D_S19.pdf",
        website: null,
    },
    {
        id: 49,
        department: "MATH",
        number: "299C",
        title: "Mathematics & Classical Music",
        facilitators: [{ name: "Siri Neerchal", email: "siri@terpmail.umd.edu" }],
        advisor: "Niranjan Ramachandran",
        credits: 1,
        description:
        "The aim of this course is to explore the historical discoveries in mathematics that have influenced Western classical music, as well as musical expressions of specific mathematical concepts. This course is not meant to be a rigorous introduction to music theory or mathematics; rather, it is focused on introducing students to classical music through mathematical ideas that appear in it. Students will also have an opportunity to explore mathematics through music in the form of a creative project.",
        syllabus: "./assets/syllabi/S19/MATH299C_S19.pdf",
        website: null,
    },
    {
        id: 50,
        department: "CMSC",
        number: "388E",
        title: "Creative Approaches to Computing: Arts and Tech",
        facilitators: [
        { name: "Astha Singhal", email: "asinghal084@gmail.com" },
        { name: "Amy Zhao", email: "zhaoamy123@gmail.com" },
        { name: "Sana Shah", email: "sana@shah.org " },
        ],
        advisor: "Roger Eastman",
        credits: 1,
        description:
        "This class aims to bring the creativity back into computing by teaching basic art and design principles through the medium of coding. By bringing together Processing, a visual arts coding language, and different hallmarks of art theory, we want to teach an innovative class that empowers students to connect with their creative side. Students should come in with basic coding knowledge but can expect to leave with a greater appreciation for digital media.",
        syllabus: "./assets/syllabi/S19/CMSC388E_S19.pdf",
        website: null,
    },
    {
        id: 51,
        department: "ENME",
        number: "289P",
        title: "Additive Manufacturing for Prosthetic Design",
        facilitators: [
        { name: "Saul Schaffer", email: "saul@umd.edu" },
        { name: "Anna Packy", email: "apacky@eng.umd.edu" },
        ],
        advisor: "Angie Bryl",
        credits: 2,
        description: "Exploring how to leverage 3D printing to improve performance and comfort of prosthetic devices.",
        syllabus: "./assets/syllabi/S19/ENME289P_S19.pdf",
        website: null,
    },
    {
        id: 52,
        department: "MATH",
        number: "299O",
        title: "Algorithms and Probability in Board Games with a Focus of Bridge",
        facilitators: [{ name: "Hakan Berk", email: "hakan.t.berk@gmail.com" }],
        advisor: "Lawrence Washington",
        credits: 1,
        description:
        "The purpose of this course is to give students an application of algorithms and probability using games such as bridge, chess, and Go. First there will be an introduction to the card game of bridge for those that have never played before. This includes a history of the game and the basics of how to play. Second, there will be an introduction to probability for those that may not have taken a class in statistics or could use a refresher. Then, the course will go in depth on how bridge is an application of probability and how it can be used to improve quickly.  Within this context, we will think about how to implement these solutions programmatically. Finally the connection between bridge, chess, and Go AI’s will be explored in the last third of the course.",
        syllabus: "./assets/syllabi/S19/MATH299O_S19.pdf",
        website: null,
    },
    {
        id: 53,
        department: "CMSC",
        number: "388I",
        title: "WebAssembly OS",
        facilitators: [{ name: "Willem Wyndham", email: "willem@cs.umd.edu" }],
        advisor: "Michael Hicks",
        credits: 1,
        description:
        "WebAssembly (wasm) is a new virtual machine designed by the four major browsers to run code almost as fast as native code. The goal is to add Operating System features to WebAssembly. To implement these features students will use AssemblyScript, a subset of Javascript which compiles to wasm.",
        syllabus: "./assets/syllabi/S19/CMSC388I_S19.pdf",
        website: null,
    },
    {
        id: 54,
        department: "CMSC",
        number: "389R",
        title: "Introduction to Ethical Hacking",
        facilitators: [
        { name: "Michael Reininger", email: null },
        { name: "Wesley Weidenhamer", email: null },
        ],
        advisor: "David Levin",
        credits: 1,
        description: "An introduction to ethical hacking geared towards entering the competitive world of cybersecurity Capture the Flag (CTF) competitions. Applications to a career in digital forensics, penetration testing, cryptology, and secure software development.",
        syllabus: null,
        website: null,
    },
    {
        id: 55,
        department: "CMSC",
        number: "389E",
        title: "Digital Logic through Minecraft",
        facilitators: [
        { name: "Alex Brassel", email: "abrassel@umd.edu" },
        { name: "Ajeet Gary", email: "agary@terpmail.umd.edu" },
        ],
        advisor: "Jason Filippou",
        credits: 1,
        description: "Explores the fundamentals of digital logic design using Minecraft's Redstone. Using the low-level and intuitive visualization ofcircuitry Redstone provides, you will create a series of projects thatapply principles of digital logic design learned in class.",
        syllabus: null,
        website: null,
    },
    // {
    //   id: 56,
    //   department: "AASP",
    //   number: "299I",
    //   title: "Elementary Igbo II",
    //   facilitators: [
    //     { name: "TBD", email: null },
    //   ],
    //   advisor: "Sangeetha Madhavan",
    //   credits: 1,
    //   description:
    //     "...",
    //   syllabus: null,
    //   website: null,
    // },
    {
        id: 57,
        department: "AASP",
        number: "299T",
        title: "Elementary Twi II",
        facilitators: [
        { name: "Maame Sapong", email: "asapong@terpmail.umd.edu" },
        { name: "Clydelle Agyei", email: "cagyei@terpmail.umd.edu" },
        ],
        advisor: "George Kintiba",
        credits: 1,
        description:
        "Akwaaba (Welcome)! This is a language course designed to provide basic communicative competence in oral Twi for beginners. We will begin by introducing students to the Ghanaian culture. As we advance through the course, you will notice that we place less emphasis on formal grammatical instruction and more emphasis on everyday speech. This is because we want to prepare you for an everyday conversation with family and friends. Through weekly lessons and activities, we hope to build your confidence when speaking Twi and also help you build a community with other students on campus.",
        syllabus: "./assets/syllabi/S19/AASP299T_S19.pdf",
        website: null,
    },
    // {
    //   id: 58,
    //   department: "AASP",
    //   number: "299Y",
    //   title: "Elemantary Yoruba II",
    //   facilitators: [
    //     { name: "TBD", email: null },
    //   ],
    //   advisor: "Jason Nichols",
    //   credits: 1,
    //   description:
    //     "...",
    //   syllabus: null,
    //   website: null,
    // },
    {
        id: 59,
        department: "IDEA",
        number: "258Z",
        title: "Digital Product Design",
        facilitators: [
        { name: "Andy Moon", email: "msoohyun88@gmail.com" },
        { name: "Chloe Jones", email: "cjones97@umd.edu" },
        ],
        advisor: "Meenu Singh",
        credits: 1,
        description:
        "Welcome to Digital Product Design! In this course you'll be introduced and immersed into user-centric design experiences for mobile and web products. You'll get to apply your learnings to real startup companies and use your design and product-thinking skills to design your own digital product. This class is for all levels of designers/builders - from newbie to pro!",
        syllabus: "./assets/syllabi/S19/IDEA258Z_S19.pdf",
        website: null,
    },
    {
        id: 60,
        department: "IDEA",
        number: "489",
        title: "Learning Experience Design Studio",
        facilitators: [
        { name: "Tianxin Chen", email: "chen128@umd.edu" },
        { name: "Ishaan Parikh", email: "parikh.i.m@gmail.com" },
        ],
        advisor: "Meenu Singh",
        credits: 2,
        description: "In this class, we will deconstruct the elements of a learning experience and consider each element as a variable to experiment with in your teaching. You will also have the opportunity to share and discuss your teaching experiences with fellow facilitators.",
        syllabus: "https://docs.google.com/document/d/1xaSIhIQpPZdrm8lI4tw9Xk1NfAertoY7Cu99AmCMjXk/edit?usp=sharing",
        website: null,
    },
    {
        id: 61,
        department: "MATH",
        number: "299M",
        title: "Visualization through Mathematica",
        facilitators: [{ name: "Ajeet Gary", email: "agary@terpmail.umd.edu" }],
        advisor: "William Goldman",
        credits: 1,
        description:
        "A comprehensive course on the technical computing language Mathematica, starting with basics including plotting, computation, 3D modeling, and interactive output. The last weeks focus on advanced topics including parallelization, evaluation control, precomputation, and advanced dynamic functionality. The course culminates in personalized final projects on a topic of each student's choice - application vary from physics to finance to nueroscience and more.",
        syllabus: "./assets/syllabi/S19/MATH299M_S19.pdf",
        website: null,
    },
    {
        id: 62,
        department: "CMSC",
        number: "388G",
        title: "Virtual Reality Game Development",
        facilitators: [{ name: "Galen Stetsyuk", email: "stetsyuk@umd.edu" }],
        advisor: "Ashok Agrawala",
        credits: 1,
        description:
        "Explores the virtual reality game development best practices and use of commercial game engines to build VR experiences that are engaging, immersive, and reduce the onset of simulation sickness. Also, focuses on development with Unreal Engine using C++, using 3d models, lighting, and graphics to optimize experiences for VR.",
        syllabus: "./assets/syllabi/S19/CMSC388G_S19.pdf",
        website: null,
    },
    {
        id: 63,
        department: "CMSC",
        number: "389J",
        title: "Introduction to Reverse Engineering",
        facilitators: [
        { name: "Drake Petersen", email: "drakemp@terpmail.umd.edu" },
        { name: "Christopher Brown", email: "chris03@terpmail.umd.edu" },
        ],
        advisor: "Jonathan Katz",
        credits: 1,
        description:
        "The course will assist students in gaining experience in a high demand practice of cybersecurity through weekly reversing assignments. Students will be challenged to think outside the box in order to solve reversing challenges. Assignments will be challenges focused in the analysis of Linux binaries including various malware. The goal is to have students go from beginner to intermediate level reverse engineers. Students will be expected to have some assembly experience prior to the class (calling conventions, stack/heap, registers), but students will be taught x86_64 assembly as the semester progresses.",
        syllabus: "./assets/syllabi/S19/CMSC389J_S19.pdf",
        website: null,
    },
    {
        id: 64,
        department: "MUSC",
        number: "248D",
        title: "Analysis of Hip Hop Music",
        facilitators: [
        { name: "Yannick Alexis", email: "yannickalexis@gmail.com" },
        { name: "Jordan Weber", email: "jwebs2@umd.edu" },
        ],
        advisor: "William Evans",
        credits: 1,
        description:
        "This course will discuss the history and analyze the evolution of Hip Hop and rap music from it’s early stages in the Nineteen Eighties to the Present day. Students will interact in class discussions and gain an understanding for the different sounds, messages, and impacts ofvarying Hip Hop artists and styles. From this, students will then apply learning from in class discussion by exploring previously unheard music and articulating their opinions. Throughout the course students will reflect on the value of Hip Hop to society and how it affects culture. Students will also get the chance to interact with local Hip-Hop artists as well as write and perform their own art as an extended learning opportunity to connect with the art form. Overall, students will learn and evaluate the intricacies of Hip Hop music and it’s importance to society.",
        syllabus: null,
        website: null,
    },
    ],
}